# Generated by Django 5.2.11 on 2026-03-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_add_eligibility_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded resume (PDF, DOC)', null=True, upload_to='resumes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True, help_text='Resume content in JSON or formatted text (optional if file is uploaded)'),
        ),
    ]
